---
name: Run smoke tests

on:
  workflow_call:

jobs:
  smote-test:
    name: Smoke test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 2
      
      - name: Checkout reusable workflows repo
        uses: actions/checkout@v3
        with:
          repository: vyos/.github
          path: reusable-workflows
          ref: feature/T6349-reusable-workflows
        
      - name: Install Pipenv
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pipenv

      - name: Run smoke test
        timeout-minutes: 10
        run: |
          pipenv install --dev
          pipenv install -r ./reusable-workflows/.github/test-requirements.txt
          pipenv run make test