---
name: Trigger repo sync

on:
  workflow_call:
    inputs:
      REMOTE_OWNER:
        description: 'Remote repo owner'
        type: string
        required: true
      REMOTE_REPO:
        description: 'Remote repo name'
        type: string
        required: true
      PAT:
        description: 'Personal Access Token'
        type: string
        required: true

jobs:
  trigger-repo-sync:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:

      - name: Trigger sync workflow
        shell: bash
        run: |
          echo "Triggering sync workflow for ${{ inputs.REMOTE_OWNER }}/${{ inputs.REMOTE_REPO }}"
          echo "Triggering sync workflow with PAT ${{ inputs.PAT }}"
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ inputs.PAT }}" \
            https://api.github.com/repos/${{ inputs.REMOTE_OWNER }}/${{ inputs.REMOTE_REPO }}/actions/workflows/vyos-repo-sync.yml/dispatches \
            -d '{"ref":"git-actions"}'
