---
name: Trigger repo sync

on:
  workflow_call:

jobs:
  trigger-repo-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Trigger sync workflow
        shell: bash
        env:
          REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
          REMOTE_OWNER: ${{ secrets.REMOTE_OWNER }}
          PAT: ${{ secrets.PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer $PAT" \
            https://api.github.com/repos/$REMOTE_OWNER/$REMOTE_REPO/actions/workflows/vyos-repo-sync.yml/dispatches \
            -d '{"ref":"git-actions"}'
